# Generated by Django 4.2.1 on 2023-05-30 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_alter_test_t"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Test",
        ),
    ]
