# Generated by Django 4.2.1 on 2023-05-30 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_delete_test"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_admin",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has permissions to access all dashboard.",
                verbose_name="Admin",
            ),
        ),
    ]
